import {getJson,mutateJson} from './state-store.mjs';
const KEY='agent-farm';
const seed=()=>({version:1,enabled:true,cycles:0,lastCycleAt:null,missions:[],teams:[],lessons:[],metrics:{teamsAssembled:0,tasksPlanned:0}});
export const ROLE_LIBRARY=Object.freeze({
 strategist:{goal:'Turn the business goal into a ranked strategy and measurable milestones.',tools:['market-signals','portfolio-prioritization','goal-decomposition']},
 chiefOfStaff:{goal:'Assemble agents, assign work, resolve dependencies and monitor execution.',tools:['role-routing','dependency-graph','progress-review']},
 opportunityScout:{goal:'Find lawful high-value buyer problems and demand signals.',tools:['public-research','demand-scoring','buyer-segmentation']},
 researcher:{goal:'Collect evidence, alternatives and constraints from lawful sources.',tools:['evidence-ranking','source-summary','competitive-landscape']},
 analyst:{goal:'Quantify opportunity, funnel and outcome performance.',tools:['unit-economics','funnel-analysis','experiment-analysis']},
 productBuilder:{goal:'Convert validated needs into original digital products and software specs.',tools:['product-spec','workflow-design','acceptance-criteria']},
 sourceArchitect:{goal:'Convert observed capability into clean-room interfaces, data models and tests.',tools:['architecture','api-contract','data-model','test-plan']},
 codeBuilder:{goal:'Generate independently authored source code for approved specifications.',tools:['code-generation','refactoring','test-generation']},
 designer:{goal:'Design usable interfaces and customer journeys.',tools:['ux-flow','ui-spec','accessibility-review']},
 marketer:{goal:'Create truthful positioning and acquisition experiments.',tools:['seo','owned-content','creative-testing','permissioned-social']},
 copywriter:{goal:'Create clear human-centered product and campaign copy without unsupported claims.',tools:['landing-copy','offer-copy','ad-variants']},
 sales:{goal:'Match qualified buyer needs to truthful offers and buyer-initiated checkout.',tools:['qualification','proposal','follow-up-plan']},
 payment:{goal:'Route checkout to PayPal and count only provider-verified completed captures.',tools:['paypal-orders','payment-verification']},
 fulfillment:{goal:'Deliver entitled digital products only after verified payment.',tools:['delivery-entitlement','artifact-packaging']},
 risk:{goal:'Block unsafe, deceptive, infringing or unauthorized actions.',tools:['compliance-gate','ip-review','security-review']},
 critic:{goal:'Adversarially review assumptions, code, offers and tests before release.',tools:['red-team-review','failure-mode-analysis','quality-gate']},
 growth:{goal:'Scale only channels with real qualified traffic and conversion evidence.',tools:['attribution','channel-ranking','budgetless-growth']},
 learner:{goal:'Record outcomes and convert them into reusable skills and playbooks.',tools:['postmortem','skill-extraction','playbook-update']}
});
const PIPELINE=['STRATEGY','TEAM_ASSEMBLY','OPPORTUNITY_SCAN','RESEARCH','COMPETITOR_GAP','PRODUCT_SPEC','CLEAN_ROOM_SOURCE_PLAN','BUILD','CRITIQUE','QA','PUBLISH','PROMOTE','SELL','PAYMENT_VERIFY','FULFILL','MEASURE','LEARN'];
function requiredRoles(mission=''){const m=String(mission).toLowerCase();const base=['strategist','chiefOfStaff','opportunityScout','researcher','analyst','risk','critic','learner'];if(/app|software|code|system|agent|automation/.test(m))base.push('productBuilder','sourceArchitect','codeBuilder','designer');else base.push('productBuilder');if(/sell|revenue|market|product|customer|business/.test(m))base.push('marketer','copywriter','sales','payment','fulfillment','growth');return [...new Set(base)]}
export function assembleTeam({mission='Build and sell useful AI products',goal='',constraints=[]}={}){const roles=requiredRoles(mission);return {id:'team-'+crypto.randomUUID(),mission:String(mission),goal:String(goal||mission),constraints:constraints.map(String),roles:roles.map(id=>({id,...ROLE_LIBRARY[id],status:'active'})),pipeline:PIPELINE,createdAt:new Date().toISOString()}}
export function missionPlan(input={}){const team=assembleTeam(input);return {team,tasks:team.pipeline.map((stage,i)=>({id:`${team.id}-task-${i+1}`,stage,owner:stage==='STRATEGY'?'strategist':stage==='TEAM_ASSEMBLY'?'chiefOfStaff':stage==='OPPORTUNITY_SCAN'?'opportunityScout':stage==='RESEARCH'||stage==='COMPETITOR_GAP'?'researcher':stage==='PRODUCT_SPEC'?'productBuilder':stage==='CLEAN_ROOM_SOURCE_PLAN'?'sourceArchitect':stage==='BUILD'?'codeBuilder':stage==='CRITIQUE'||stage==='QA'?'critic':stage==='PUBLISH'||stage==='PROMOTE'?'marketer':stage==='SELL'?'sales':stage==='PAYMENT_VERIFY'?'payment':stage==='FULFILL'?'fulfillment':stage==='MEASURE'?'analyst':'learner',status:i===0?'ready':'blocked',acceptance:stage==='PAYMENT_VERIFY'?'Provider-confirmed completed PayPal capture':stage==='CLEAN_ROOM_SOURCE_PLAN'?'Independent specification and interfaces; no proprietary code extraction':'Stage output passes risk and quality gate'}))}}
export async function runAgentFarmCycle({mission='Operate ULTRON autonomous business',goal='Create, market, sell and improve useful original products',constraints=[]}={}){const plan=missionPlan({mission,goal,constraints});return mutateJson(KEY,seed(),async s=>{s.enabled=true;s.cycles++;s.lastCycleAt=new Date().toISOString();s.missions.unshift({at:s.lastCycleAt,mission,goal,status:'active'});s.missions=s.missions.slice(0,100);s.teams.unshift(plan.team);s.teams=s.teams.slice(0,30);s.metrics={teamsAssembled:(s.metrics?.teamsAssembled||0)+1,tasksPlanned:(s.metrics?.tasksPlanned||0)+plan.tasks.length,activeRoles:plan.team.roles.length};s.currentPlan=plan;s.lessons.unshift({at:s.lastCycleAt,rule:'Scale evidence-backed capabilities; generate original source from observable behavior; preserve licenses; verify payments before fulfillment.'});s.lessons=s.lessons.slice(0,100)})}
export async function agentFarmState(){return getJson(KEY,seed())}
export function agentFarmManifest(){return {mode:'MODULAR_AI_FARM',purpose:'Assemble specialized agents per mission instead of pretending one model is an entire company.',roleCount:Object.keys(ROLE_LIBRARY).length,roles:ROLE_LIBRARY,pipeline:PIPELINE,principles:['assemble the smallest capable team for each mission','specialists share a common project state','chief-of-staff coordinates dependencies','critic and risk gates precede publishing','source code is independently authored from specs or legitimately licensed source','real outcomes update reusable playbooks','no fake traffic, spam, impersonation, credential theft or proprietary-code extraction']}}
