// ULTRON AI Market — digital products generated by AI-assisted workflows.
// Products must be original/useful, truthfully described, and priced from $1–$999.

export const AI_MARKET_RULES=Object.freeze({
  currency:'USD',minPrice:1,maxPrice:999,
  fulfillment:'digital-after-verified-payment',
  accounting:'verified-payments-only',
  prohibited:['copyright-infringement','counterfeit-content','deceptive-claims','fake-reviews','fabricated-revenue','spam','phishing','unauthorized-charges']
});

export const AI_MARKET_CATALOG=Object.freeze([
 {id:'prompt-mini',name:'AI Prompt Mini Pack',price:1,category:'prompts',description:'Original starter prompt pack for everyday business tasks.'},
 {id:'caption-pack',name:'30-Day Caption Pack',price:9,category:'content',description:'Original social caption framework with 30 editable prompts.'},
 {id:'email-kit',name:'Business Email Kit',price:19,category:'templates',description:'Editable customer-service and sales email templates.'},
 {id:'content-calendar',name:'90-Day Content Calendar',price:39,category:'content',description:'Editable content planning system with themes and publishing prompts.'},
 {id:'lead-playbook',name:'Lead Follow-Up Playbook',price:79,category:'sales',description:'Lead qualification and permitted follow-up workflow templates.'},
 {id:'website-kit',name:'AI Website Launch Kit',price:149,category:'website',description:'Landing-page brief, copy framework, launch checklist and analytics plan.'},
 {id:'automation-blueprint',name:'Business Automation Blueprint',price:299,category:'automation',description:'Customizable automation architecture and implementation checklist.'},
 {id:'growth-system',name:'AI Growth System',price:499,category:'growth',description:'Productized acquisition, content, conversion and measurement operating system.'},
 {id:'agent-stack',name:'AI Agent Business Stack',price:999,category:'automation',description:'Premium multi-agent workflow specification, templates and deployment plan.'}
]);

export function validateMarketProduct(p){
 if(!p||typeof p!=='object')throw Error('Product required');
 const price=Number(p.price);if(!Number.isFinite(price)||price<1||price>999)throw Error('AI Market price must be $1-$999');
 if(!String(p.name||'').trim()||!String(p.description||'').trim())throw Error('Name and description required');
 return {...p,price:Number(price.toFixed(2)),currency:'USD'};
}
export function marketProduct(id){return AI_MARKET_CATALOG.find(p=>p.id===id)||null}
export function marketStats(){return {products:AI_MARKET_CATALOG.length,minPrice:Math.min(...AI_MARKET_CATALOG.map(x=>x.price)),maxPrice:Math.max(...AI_MARKET_CATALOG.map(x=>x.price)),currency:'USD'}}
export function buildDigitalDelivery(product,orderId){
 const p=validateMarketProduct(product);return {
  type:'AI_MARKET_DIGITAL_PRODUCT',productId:p.id,orderId,
  title:p.name,
  sections:[
   {title:'Start Here',body:`This ${p.name} package is an original AI-assisted digital resource. Customize it to your business and verify factual claims before publishing.`},
   {title:'Implementation',body:`Use the included ${p.category} framework to define your audience, desired outcome, workflow, acceptance criteria and measurement plan.`},
   {title:'Quality Checklist',body:'Review for accuracy, originality, permissions, accessibility, privacy, brand fit and measurable usefulness before external use.'}
  ],
  generatedAt:new Date().toISOString()
 };
}
