import {getJson,mutateJson} from './state-store.mjs';
const KEY='business-os-state';
const seed=()=>({version:1,cycles:0,lastCycleAt:null,opportunities:[],campaigns:[],metrics:{activated:0},history:[]});
const DOMAINS=[
{id:'appointments',problem:'missed appointments and slow booking follow-up',buyers:['clinics','salons','home services','consultants'],formats:['appointment follow-up automation','booking recovery kit','reminder workflow'],risk:'low'},
{id:'resume',problem:'slow resume tailoring and application preparation',buyers:['job seekers','career coaches','recruiting firms'],formats:['resume optimizer','application tracker','interview prep kit'],risk:'low'},
{id:'meetings',problem:'meetings create notes but no accountable follow-through',buyers:['agencies','sales teams','professional services'],formats:['meeting agenda creator','action-item workflow','follow-up pack'],risk:'low'},
{id:'pricing',problem:'teams lack structured competitor and pricing comparisons',buyers:['ecommerce teams','SaaS teams','agencies'],formats:['competitor tracker','pricing optimizer worksheet','market comparison report'],risk:'low'},
{id:'reviews',problem:'customer feedback is collected but not converted into action',buyers:['local businesses','ecommerce teams','hospitality'],formats:['review response workflow','feedback analyzer','voice-of-customer dashboard'],risk:'low'},
{id:'data',problem:'business data is scattered and decisions are delayed',buyers:['software companies','consulting businesses','recruiting firms','startups'],formats:['sales dashboard','customer churn worksheet','inventory forecast','market research report'],risk:'low'},
{id:'legal-docs',problem:'teams spend time triaging long contracts and policy documents',buyers:['legal operations teams','procurement teams','small businesses'],formats:['document issue-spotting checklist','contract intake workflow','clause comparison worksheet'],risk:'high'},
{id:'marketing',problem:'teams need more creative variants and structured ad tests',buyers:['startups','ecommerce brands','agencies'],formats:['copy variant pack','ad testing planner','creative brief generator'],risk:'low'},
{id:'security',problem:'small teams lack repeatable security hygiene workflows',buyers:['startups','agencies','professional services'],formats:['security checklist','incident readiness worksheet','vendor review pack'],risk:'medium'},
{id:'recruiting',problem:'candidate intake and follow-up are inconsistent',buyers:['recruiting firms','HR teams','startups'],formats:['candidate scorecard','follow-up workflow','interview planner'],risk:'medium'}
];
function score(d,i,ledger){const paid=Object.values(ledger?.orders||{}).filter(o=>o?.status==='COMPLETED').length;const base=72+((i*11+paid*3)%24);return Math.min(99,base)}
export function opportunityMap(ledger={}){return DOMAINS.map((d,i)=>({...d,score:score(d,i,ledger),evidenceNeeded:['buyer pain','existing spend/alternatives','clear measurable outcome'],competitionPlan:['identify direct and indirect alternatives','compare price, proof, speed, friction and buyer fit','differentiate on measurable usefulness, not unsupported claims'],activationRule:d.risk==='high'?'human/compliance review before external claims':'quality gate then publish'})).sort((a,b)=>b.score-a.score)}
export function productIdeasForOpportunity(o,count=6){const out=[];for(let i=0;i<count;i++){const f=o.formats[i%o.formats.length],b=o.buyers[i%o.buyers.length];out.push({name:f+' for '+b,buyer:b,problem:o.problem,format:f,positioning:'Help '+b+' reduce '+o.problem+' with a practical, measurable workflow.',competitionPlan:o.competitionPlan,risk:o.risk})}return out}
export function commandBridge(){return {channels:['website events','PayPal payment events','project state','market/research feeds','authorized social/email connectors when connected'],roles:['OpportunityAgent','CompetitionAgent','ProductFactoryAgent','CriticAgent','GrowthAgent','SalesAgent','PaymentAgent','FulfillmentAgent','AnalyticsAgent','RiskAgent'],loop:['observe demand','rank opportunity','research alternatives','generate candidates','critique and quality-check','publish owned product page','create compliant promotion drafts','route buyer to PayPal','fulfill after verified capture','attribute outcome','update rankings']}}
export function targetProfile(o){return {buyers:o.buyers,budgetSignal:'prioritize organizations already paying for software, services or workflow improvement',needSignal:o.problem,qualification:['clear relevant need','lawful/public or consented contact source','ability to benefit','no deceptive personalization'],outreach:'permissioned channels only; no spam or impersonation'}}
export async function runBusinessOSCycle({ledger={},baseUrl=''}={}){const opps=opportunityMap(ledger),top=opps.slice(0,5);return mutateJson(KEY,seed(),async s=>{s.cycles++;s.lastCycleAt=new Date().toISOString();s.opportunities=opps.slice(0,20);s.campaigns=top.flatMap(o=>productIdeasForOpportunity(o,3).map(p=>({opportunityId:o.id,...p,status:'draft-owned-channel',landingBase:baseUrl?baseUrl+'/market':'/market'}))).slice(0,30);s.metrics={activated:s.campaigns.length,completedPayments:Object.values(ledger?.orders||{}).filter(o=>o?.status==='COMPLETED').length};s.history.unshift({at:s.lastCycleAt,type:'business-os-cycle',top:top.map(x=>x.id)});s.history=s.history.slice(0,500)})}
export async function businessOSState(){return getJson(KEY,seed())}
export function businessOSManifest(){return {mode:'24/7 autonomous operations within authorized systems',commandBridge:commandBridge(),domains:DOMAINS.map(({id,problem,buyers,risk})=>({id,problem,buyers,risk})),principles:['no physical inventory required','sell original digital products/workflows','find buyers by need and budget signals','research competition before positioning','generate multiple candidates before selection','use owned SEO/product pages first','use permissioned social/email/affiliate distribution when connected','PayPal verified payments only','automated fulfillment after verified capture','feedback loop reallocates effort toward real conversions'],guardrails:['no fake traffic','no spam','no phishing','no fabricated revenue','no unauthorized charges','no legal/medical/financial professional claims without appropriate review']}}