import {createServer} from 'node:http';
import {fileURLToPath} from 'node:url';
import {marketProduct,marketStats,marketStores,catalogPage,buildDigitalDelivery,featuredProducts} from './ai-market.mjs';
import {assertCaptureMatches,renderFulfillmentHtml,verifyPayPalRuntime} from './payment-runtime.mjs';
import {ledger,saveLedger} from './ledger-store.mjs';
import {storeHealth} from './state-store.mjs';
import {runAgentCycle,agentState} from './agents.mjs';
import {wizardFromConversation,generateCandidates,critiqueCandidate,buildAcquisitionPlan,prospectToPaymentWorkflow,capabilityManifest} from './ultron2-core.mjs';
import {saveProject,getProject,listProjects,updateProjectProgress} from './project-store.mjs';
import {productCritiqueSystem,appFactorySystem,prospectRevenueSystem,wizardOperatingSystem,unifiedVideoArchitecture} from './video-systems.mjs';
import {runBusinessOSCycle,businessOSState,businessOSManifest,opportunityMap,productIdeasForOpportunity,targetProfile,commandBridge} from './business-os.mjs';
import {agentFarmState,agentFarmManifest,missionPlan} from './agent-farm.mjs';
import {autopilotState,productionTerminal} from './autopilot-mode.mjs';
import {answerQuestion} from './support.js';
import {masterCapabilityManifest,marketVideoPlan,cryptoVideoPlan,buildMission} from './video-master-pack.mjs';
import {expansionManifest,contentMission,businessOpportunityMission,cryptoResearchMission,animatedMediaMission} from './video-expansion-pack.mjs';
import {acquisitionPlan,outreachDraft} from './audience-acquisition.mjs';
import {revenueLoopStatus,flagshipOffer,DEMAND_EVIDENCE} from './revenue-loop.mjs';
const BASE='https://api-m.paypal.com',CID=process.env.PAYPAL_CLIENT_ID||'',SECRET=process.env.PAYPAL_CLIENT_SECRET||'',WH=process.env.PAYPAL_WEBHOOK_ID||'',PUBLIC=(process.env.PUBLIC_BASE_URL||'').replace(/\/$/,''),READY=Boolean(CID&&SECRET&&WH&&PUBLIC);
const WORKLOAD=Math.max(1,Math.min(10,Number(process.env.ULTRON_WORKLOAD_MULTIPLIER||3))),INTERVAL=Math.max(5,Number(process.env.AGENT_INTERVAL_MINUTES||5));
let cache={token:null,exp:0},payment={ok:false,checkedAt:null},timer=null;
async function token(){if(cache.token&&Date.now()<cache.exp-60000)return cache.token;const r=await fetch(BASE+'/v1/oauth2/token',{method:'POST',headers:{authorization:'Basic '+Buffer.from(CID+':'+SECRET).toString('base64'),'content-type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'}),d=await r.json();if(!r.ok)throw Error('PayPal OAuth failed');cache={token:d.access_token,exp:Date.now()+Number(d.expires_in||300)*1000};return cache.token}
async function paypal(path,method='GET',body=null,rid=null){const h={authorization:'Bearer '+await token(),'content-type':'application/json'};if(rid)h['paypal-request-id']=rid;const r=await fetch(BASE+path,{method,headers:h,body:body?JSON.stringify(body):undefined}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||`PayPal ${r.status}`);return d}
async function createOrder(key){const p=marketProduct(key);if(!p)throw Error('Unknown product');const amount=Number(p.price).toFixed(2),o=await paypal('/v2/checkout/orders','POST',{intent:'CAPTURE',purchase_units:[{reference_id:key,description:p.name,amount:{currency_code:'USD',value:amount}}],payment_source:{paypal:{experience_context:{user_action:'PAY_NOW',return_url:PUBLIC+'/paypal/return',cancel_url:PUBLIC+'/paypal/cancel'}}}},'create-'+key+'-'+crypto.randomUUID()),approve=(o.links||[]).find(x=>x.rel==='payer-action'||x.rel==='approve')?.href;if(!o.id||!approve)throw Error('No approval URL');await saveLedger(l=>{l.orders[o.id]={id:o.id,product:key,name:p.name,amount,currency:'USD',market:true,storeId:p.storeId,status:o.status,createdAt:new Date().toISOString()}});return approve}
async function capture(id){const o=await paypal('/v2/checkout/orders/'+encodeURIComponent(id)+'/capture','POST',{},'capture-'+id);return o.purchase_units?.flatMap(u=>u.payments?.captures||[])[0]||null}
async function fulfill(id,c){let out;await saveLedger(l=>{const o=l.orders[id];if(!o)throw Error('Unknown order');assertCaptureMatches(o,c);if(!o.fulfillment){const p=marketProduct(o.product),d=buildDigitalDelivery(p,id);o.fulfillment={token:crypto.randomBytes(24).toString('hex'),title:p.name,summary:'ULTRON digital product',sections:d.sections,createdAt:d.generatedAt}}o.status='COMPLETED';o.captureId=String(c.id||o.captureId||'');o.capturedAt=o.capturedAt||new Date().toISOString();o.capturedAmount=Number(c.amount?.value||o.amount||0);out=o.fulfillment});return out}
async function byToken(t){const l=await ledger();return Object.values(l.orders||{}).find(o=>o?.fulfillment?.token===t)?.fulfillment||null}
async function agentBurst(){const l=await ledger();for(let i=0;i<WORKLOAD;i++)await runAgentCycle({ledger:l,baseUrl:PUBLIC});await runBusinessOSCycle({ledger:l,baseUrl:PUBLIC})}
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shell=(title,body,head='')=>`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${esc(title)}</title>${head}<style>body{background:#090c10;color:#fff;font:15px system-ui;max-width:1250px;margin:auto;padding:24px}nav{display:flex;gap:8px;flex-wrap:wrap}a{color:#8cff8c}section{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}article{background:#141920;padding:18px;border-radius:14px}b{font-size:28px;color:#6ee77a}input{padding:10px;min-width:260px}button{padding:10px}</style></head><body>${body}</body></html>`;
function marketHtml(id,page=1,q=''){const stores=marketStores(),store=id?stores.find(x=>x.id===id):null,per=60,total=store?.products||marketStats().products,pages=Math.ceil(total/per),p=Math.max(1,Math.min(page,pages)),items=catalogPage({storeId:id||undefined,offset:(p-1)*per,limit:per,query:q}),nav=stores.map(x=>`<a href="/market/${x.id}">${esc(x.name)}</a>`).join(' ');return shell(store?.name||'ULTRON AI Market',`<h1>${esc(store?.name||'ULTRON AI Market Network')}</h1><p>10 stores · ${marketStats().products.toLocaleString()} digital products · $1–$10,000 · PayPal checkout · verified-payment fulfillment.</p><form><input name="q" value="${esc(q)}" placeholder="Search products"><button>Search</button></form><nav>${nav}</nav><section>${items.map(x=>`<article><small>${esc(x.category)}</small><h3><a href="/product/${x.id}">${esc(x.name)}</a></h3><b>$${x.price}</b><p>${esc(x.description)}</p><a href="/product/${x.id}">View product</a></article>`).join('')}</section><p>Page ${p}/${pages}</p>`)}
function productHtml(p){const url=`${PUBLIC}/product/${p.id}`,schema={"@context":"https://schema.org","@type":"Product",name:p.name,description:p.description,sku:p.id,category:p.category,brand:{"@type":"Brand",name:"ULTRON AI Market"},offers:{"@type":"Offer",url,priceCurrency:"USD",price:String(p.price),availability:"https://schema.org/InStock"}};return shell(p.name,`<nav><a href="/market">← AI Market</a><a href="/market/${p.storeId}">More in ${esc(p.category)}</a></nav><article><small>${esc(p.category)}</small><h1>${esc(p.name)}</h1><b>$${p.price}</b><p>${esc(p.description)}</p><h2>What you get</h2><p>An original digital implementation resource with a framework, execution worksheet, opportunity score, optimization loop and quality/compliance gate.</p><a href="/buy?product=${p.id}">Buy securely with PayPal</a></article>`,`<meta name="description" content="${esc(p.description)}"><link rel="canonical" href="${esc(url)}"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script>`)}
function sitemap(index=0){const stores=marketStores(),chunk=10000,start=index*chunk,end=Math.min(marketStats().products,start+chunk),urls=[];for(let n=start;n<end;n++){const perStore=marketStats().productsPerStore,si=Math.floor(n/perStore),local=n%perStore+1;if(!stores[si])break;urls.push(`<url><loc>${PUBLIC}/product/${stores[si].id}-${String(local).padStart(8,'0')}</loc></url>`)}return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.join('')}</urlset>`}
function sitemapStatic(){const paths=['/market','/solutions/missed-lead-recovery','/revenue-loop','/insights'];return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${paths.map(p=>`<url><loc>${PUBLIC}${p}</loc></url>`).join('')}</urlset>`}
function sitemapIndex(){const count=Math.ceil(marketStats().products/10000);return `<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><sitemap><loc>${PUBLIC}/sitemap-static.xml</loc></sitemap>${Array.from({length:count},(_,i)=>`<sitemap><loc>${PUBLIC}/sitemap-${i}.xml</loc></sitemap>`).join('')}</sitemapindex>`}
export function createApp(){return createServer(async(req,res)=>{const u=new URL(req.url,'http://local'),path=u.pathname,json=(s,d)=>{res.writeHead(s,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(d))};try{
if(path==='/'){res.writeHead(200,{'content-type':'text/html'});return res.end(shell('ULTRON','<h1>ULTRON</h1><p><a href="/market">Open AI Market</a> · <a href="/solutions/missed-lead-recovery">Flagship offer</a> · <a href="/revenue-loop">Revenue Loop</a> · <a href="/support">Support</a></p>'))}
if(path==='/support'){res.writeHead(200,{'content-type':'text/html'});return res.end(shell('ULTRON Support','<h1>ULTRON Support</h1><p>Ask about products, checkout, delivery or refund policy through the support API.</p><p><a href="/market">Back to AI Market</a></p>'))}
if(path==='/api/support'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;let body;try{body=JSON.parse(raw||'{}')}catch{return json(400,{error:'invalid JSON'})}try{return json(200,{ok:true,...answerQuestion(body.question)})}catch(e){return json(400,{error:String(e?.message||e)})}}
if(path==='/health'){const db=await storeHealth(),a=await agentState();return json(db.ok?200:503,{ok:db.ok,database:db,aiMarket:{ready:true,...marketStats()},paymentReady:READY&&payment.ok,agents:{lastCycleAt:a.metrics?.lastCycleAt||null,intervalMinutes:INTERVAL,workloadMultiplier:WORKLOAD}})}
if(path==='/robots.txt'){res.writeHead(200,{'content-type':'text/plain'});return res.end(`User-agent: *\nAllow: /\nSitemap: ${PUBLIC}/sitemap.xml\n`)}
if(path==='/sitemap.xml'){res.writeHead(200,{'content-type':'application/xml'});return res.end(sitemapIndex())}
if(path==='/sitemap-static.xml'){res.writeHead(200,{'content-type':'application/xml','cache-control':'public,max-age=3600'});return res.end(sitemapStatic())}
if(/^\/sitemap-\d+\.xml$/.test(path)){res.writeHead(200,{'content-type':'application/xml','cache-control':'public,max-age=86400'});return res.end(sitemap(Number(path.match(/\d+/)[0])))}
if(path.startsWith('/product/')){const p=marketProduct(decodeURIComponent(path.slice(9)));if(!p)return json(404,{error:'product not found'});res.writeHead(200,{'content-type':'text/html','cache-control':'public,max-age=3600'});return res.end(productHtml(p))}
if(path==='/api/market')return json(200,{ok:true,stats:marketStats(),stores:marketStores(),featured:featuredProducts()});
if(path==='/api/revenue-loop'){const l=await ledger(),a=await agentState();return json(200,{ok:true,...revenueLoopStatus({baseUrl:PUBLIC,ledger:l,agentState:a,paymentReady:READY&&payment.ok})})}
if(path==='/revenue-loop'){const l=await ledger(),a=await agentState(),s=revenueLoopStatus({baseUrl:PUBLIC,ledger:l,agentState:a,paymentReady:READY&&payment.ok});const rows=s.stages.map(x=>`<article><small>${esc(x.deployment)} · ${esc(x.operation)}</small><h3>${esc(x.name)}</h3><p>${esc(typeof x.output==='string'?x.output:JSON.stringify(x.output))}</p></article>`).join('');res.writeHead(200,{'content-type':'text/html'});return res.end(shell('ULTRON Revenue Loop',`<h1>Demand → Revenue Loop</h1><p>The deployment is complete; recurring acquisition, measurement and agent feedback continue running.</p><p><a href="/solutions/missed-lead-recovery">Open flagship offer</a> · <a href="/market">AI Market</a></p><section>${rows}</section>`))}
if(path==='/solutions/missed-lead-recovery'){const o=flagshipOffer(PUBLIC);const evidence=DEMAND_EVIDENCE.map(x=>`<li>${esc(x.signal)}</li>`).join('');res.writeHead(200,{'content-type':'text/html','cache-control':'public,max-age=900'});return res.end(shell(o.name,`<nav><a href="/market">← AI Market</a><a href="/revenue-loop">Revenue Loop</a></nav><article><small>For ${esc(o.targetBuyer)}</small><h1>${esc(o.name)}</h1><b>${o.price}</b><p>${esc(o.positioning)}</p><h2>Why this problem</h2><ul>${evidence}</ul><h2>What you get</h2><p>Response map, lead qualification flow, booking recovery workflow, response scripts, KPI scorecard, QA/compliance gate and a 30-day optimization loop.</p><p><a href="${esc(o.checkoutPath)}">Buy securely with PayPal</a></p><p><small>No guaranteed revenue claims. Results depend on implementation, demand and the business.</small></p></article>`,`<meta name="description" content="Missed-lead response and booking recovery workflow for local service businesses."><link rel="canonical" href="${esc(o.landingUrl)}">`))}
if(path==='/api/ultron2'){const bos=await businessOSState();return json(200,{ok:true,manifest:capabilityManifest(),businessOS:businessOSManifest(),businessState:{cycles:bos.cycles,lastCycleAt:bos.lastCycleAt,metrics:bos.metrics,topOpportunities:bos.opportunities?.slice(0,5)},market:marketStats(),agentIntervalMinutes:INTERVAL,workloadMultiplier:WORKLOAD})}
if(path==='/api/business-os')return json(200,{ok:true,manifest:businessOSManifest(),state:await businessOSState()});
if(path==='/api/agent-farm')return json(200,{ok:true,manifest:agentFarmManifest(),state:await agentFarmState()});
if(path==='/api/agent-farm/plan'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;return json(200,{ok:true,plan:missionPlan(raw?JSON.parse(raw):{})})}
if(path==='/api/agent-state')return json(200,{ok:true,state:await agentState()});
if(path==='/api/autopilot'){const s=await autopilotState();return json(200,{ok:true,terminal:productionTerminal(),state:s});}
if(path==='/api/opportunities')return json(200,{ok:true,opportunities:opportunityMap(await ledger())});
if(path.startsWith('/api/opportunities/')&&path.endsWith('/products')){const id=decodeURIComponent(path.split('/')[3]);const o=opportunityMap(await ledger()).find(x=>x.id===id);if(!o)return json(404,{error:'opportunity not found'});return json(200,{ok:true,opportunity:o,target:targetProfile(o),products:productIdeasForOpportunity(o,12),commandBridge:commandBridge()})}
if(path==='/api/wizard'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;const project=wizardFromConversation(raw?JSON.parse(raw):{});await saveProject(project);return json(200,{ok:true,project})}
if(path==='/api/projects'&&req.method==='GET')return json(200,{ok:true,projects:await listProjects()});
if(path.startsWith('/api/projects/')&&req.method==='GET'){const id=decodeURIComponent(path.slice('/api/projects/'.length));const project=await getProject(id);return project?json(200,{ok:true,project}):json(404,{error:'project not found'})}
if(path==='/api/project-progress'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;const b=raw?JSON.parse(raw):{};return json(200,{ok:true,project:await updateProjectProgress(b.projectId,b.milestoneId,b.status)})}
if(path==='/api/candidates'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;return json(200,{ok:true,candidates:generateCandidates(raw?JSON.parse(raw):{})})}
if(path==='/api/critique'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;const b=raw?JSON.parse(raw):{};return json(200,{ok:true,result:critiqueCandidate(b.candidate||{},b.metrics||{})})}
if(path==='/api/acquisition-plan'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;return json(200,{ok:true,plan:buildAcquisitionPlan(raw?JSON.parse(raw):{})})}
if(path==='/api/sales-workflow'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;return json(200,{ok:true,workflow:prospectToPaymentWorkflow(raw?JSON.parse(raw):{})})}
if(path==='/api/video-systems'&&req.method==='GET')return json(200,{ok:true,architecture:unifiedVideoArchitecture(),master:masterCapabilityManifest(),market:marketVideoPlan(),crypto:cryptoVideoPlan()});
if(path==='/api/video-master'&&req.method==='GET')return json(200,{ok:true,manifest:masterCapabilityManifest(),expansion:expansionManifest()});
if(path==='/api/video-expansion'&&req.method==='GET')return json(200,{ok:true,manifest:expansionManifest(),content:contentMission({}),animatedMedia:animatedMediaMission({}),business:businessOpportunityMission({}),crypto:cryptoResearchMission({})});
if(path==='/api/acquisition'&&req.method==='GET')return json(200,{ok:true,plan:acquisitionPlan({target:Number(u.searchParams.get('target')||1000)}),draft:outreachDraft({})});
if(path==='/api/video-master/mission'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;const b=raw?JSON.parse(raw):{};return json(200,{ok:true,mission:buildMission(b)})}
if(path==='/api/video-systems/critique'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;return json(200,{ok:true,result:productCritiqueSystem(raw?JSON.parse(raw):{})})}
if(path==='/api/video-systems/app-factory'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;return json(200,{ok:true,result:appFactorySystem(raw?JSON.parse(raw):{})})}
if(path==='/api/video-systems/revenue'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;return json(200,{ok:true,result:prospectRevenueSystem(raw?JSON.parse(raw):{})})}
if(path==='/api/video-systems/wizard'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;const result=wizardOperatingSystem(raw?JSON.parse(raw):{});await saveProject(result.project);return json(200,{ok:true,result})}
if(path==='/api/search')return json(200,{ok:true,items:catalogPage({storeId:u.searchParams.get('store')||undefined,offset:Number(u.searchParams.get('offset')||0),limit:Math.min(100,Number(u.searchParams.get('limit')||20)),query:u.searchParams.get('q')||''})});
if(path==='/market'||path.startsWith('/market/')){res.writeHead(200,{'content-type':'text/html'});return res.end(marketHtml(path==='/market'?null:decodeURIComponent(path.slice(8)),Number(u.searchParams.get('page')||1),u.searchParams.get('q')||''))}
if(path==='/buy'){if(!READY)return json(503,{error:'PayPal not configured'});res.writeHead(303,{location:await createOrder(u.searchParams.get('product')||'')});return res.end()}
if((path==='/webhooks/paypal'||path==='/api/paypal/webhook')&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;let event;try{event=JSON.parse(raw||'{}')}catch{return json(400,{error:'invalid JSON'})}const verify=await paypal('/v1/notifications/verify-webhook-signature','POST',{auth_algo:req.headers['paypal-auth-algo'],cert_url:req.headers['paypal-cert-url'],transmission_id:req.headers['paypal-transmission-id'],transmission_sig:req.headers['paypal-transmission-sig'],transmission_time:req.headers['paypal-transmission-time'],webhook_id:WH,webhook_event:event});if(verify?.verification_status!=='SUCCESS')return json(400,{error:'invalid webhook signature'});if(event.event_type==='PAYMENT.CAPTURE.COMPLETED'){const cap=event.resource||{},id=cap?.supplementary_data?.related_ids?.order_id||'';if(id){try{await fulfill(id,cap);await agentBurst()}catch(e){console.error('webhook fulfillment',e)}}}return json(200,{ok:true})}
if(path==='/paypal/return'){const id=u.searchParams.get('token')||'',c=await capture(id);if(!c||c.status!=='COMPLETED')return json(409,{error:'Capture not completed'});const f=await fulfill(id,c);await agentBurst();res.writeHead(303,{location:'/fulfillment?token='+f.token});return res.end()}
if(path==='/fulfillment'){const f=await byToken(u.searchParams.get('token'));if(!f)return json(404,{error:'Not found'});res.writeHead(200,{'content-type':'text/html'});return res.end(renderFulfillmentHtml(f))}
if(path==='/paypal/cancel')return res.end('<h1>Payment canceled</h1>');
if(path==='/api/payment-status')return json(200,{provider:'PayPal',mode:'live',ready:READY&&payment.ok,runtime:payment});
return json(404,{error:'Not found'})}catch(e){console.error(e);return json(500,{error:'Request failed'})}})}
async function boot(){try{payment=await verifyPayPalRuntime({paypal,webhookId:WH,publicBaseUrl:PUBLIC})}catch(e){payment={ok:false,checkedAt:new Date().toISOString(),error:String(e?.message||e)}}console.log('ULTRON payment runtime',JSON.stringify({ok:Boolean(payment.ok),apiAuthorized:Boolean(payment.apiAuthorized),webhookEndpointVerified:Boolean(payment.webhookEndpointVerified),captureEventsSubscribed:Boolean(payment.captureEventsSubscribed),checkedAt:payment.checkedAt||null,error:payment.error||null}));if(process.env.AGENT_AUTORUN!=='false'){await agentBurst().catch(console.error);timer=setInterval(()=>agentBurst().catch(console.error),INTERVAL*60000);timer.unref?.()}}
if(process.argv[1]===fileURLToPath(import.meta.url)){createApp().listen(Number(process.env.PORT||3000),'0.0.0.0',()=>{console.log(`ULTRON market listening: ${marketStats().products} products, ${INTERVAL}m cycle, ${WORKLOAD}x workload`);boot()})}
