import {createServer} from 'node:http';
import {fileURLToPath} from 'node:url';
import {marketProduct,marketStats,marketStores,catalogPage,buildDigitalDelivery} from './ai-market.mjs';
import {assertCaptureMatches,renderFulfillmentHtml,verifyPayPalRuntime} from './payment-runtime.mjs';
import {ledger,saveLedger} from './ledger-store.mjs';
import {storeHealth} from './state-store.mjs';
import {runAgentCycle,agentState} from './agents.mjs';
import {wizardFromConversation,generateCandidates,critiqueCandidate,buildAcquisitionPlan,prospectToPaymentWorkflow,capabilityManifest} from './ultron2-core.mjs';
import {saveProject,getProject,listProjects,updateProjectProgress} from './project-store.mjs';
import {productCritiqueSystem,appFactorySystem,prospectRevenueSystem,wizardOperatingSystem,unifiedVideoArchitecture} from './video-systems.mjs';
const BASE='https://api-m.paypal.com',CID=process.env.PAYPAL_CLIENT_ID||'',SECRET=process.env.PAYPAL_CLIENT_SECRET||'',WH=process.env.PAYPAL_WEBHOOK_ID||'',PUBLIC=(process.env.PUBLIC_BASE_URL||'').replace(/\/$/,''),READY=Boolean(CID&&SECRET&&WH&&PUBLIC);
const WORKLOAD=Math.max(1,Math.min(10,Number(process.env.ULTRON_WORKLOAD_MULTIPLIER||3))),INTERVAL=Math.max(5,Number(process.env.AGENT_INTERVAL_MINUTES||5));
let cache={token:null,exp:0},payment={ok:false,checkedAt:null},timer=null;
async function token(){if(cache.token&&Date.now()<cache.exp-60000)return cache.token;const r=await fetch(BASE+'/v1/oauth2/token',{method:'POST',headers:{authorization:'Basic '+Buffer.from(CID+':'+SECRET).toString('base64'),'content-type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'}),d=await r.json();if(!r.ok)throw Error('PayPal OAuth failed');cache={token:d.access_token,exp:Date.now()+Number(d.expires_in||300)*1000};return cache.token}
async function paypal(path,method='GET',body=null,rid=null){const h={authorization:'Bearer '+await token(),'content-type':'application/json'};if(rid)h['paypal-request-id']=rid;const r=await fetch(BASE+path,{method,headers:h,body:body?JSON.stringify(body):undefined}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||`PayPal ${r.status}`);return d}
async function createOrder(key){const p=marketProduct(key);if(!p)throw Error('Unknown product');const amount=Number(p.price).toFixed(2),o=await paypal('/v2/checkout/orders','POST',{intent:'CAPTURE',purchase_units:[{reference_id:key,description:p.name,amount:{currency_code:'USD',value:amount}}],payment_source:{paypal:{experience_context:{user_action:'PAY_NOW',return_url:PUBLIC+'/paypal/return',cancel_url:PUBLIC+'/paypal/cancel'}}}},'create-'+key+'-'+crypto.randomUUID()),approve=(o.links||[]).find(x=>x.rel==='payer-action'||x.rel==='approve')?.href;if(!o.id||!approve)throw Error('No approval URL');await saveLedger(l=>{l.orders[o.id]={id:o.id,product:key,name:p.name,amount,currency:'USD',market:true,storeId:p.storeId,status:o.status,createdAt:new Date().toISOString()}});return approve}
async function capture(id){const o=await paypal('/v2/checkout/orders/'+encodeURIComponent(id)+'/capture','POST',{},'capture-'+id);return o.purchase_units?.flatMap(u=>u.payments?.captures||[])[0]||null}
async function fulfill(id,c){let out;await saveLedger(l=>{const o=l.orders[id];if(!o)throw Error('Unknown order');assertCaptureMatches(o,c);if(!o.fulfillment){const p=marketProduct(o.product),d=buildDigitalDelivery(p,id);o.fulfillment={token:crypto.randomBytes(24).toString('hex'),title:p.name,summary:'ULTRON digital product',sections:d.sections,createdAt:d.generatedAt}}o.status='COMPLETED';out=o.fulfillment});return out}
async function byToken(t){const l=await ledger();return Object.values(l.orders||{}).find(o=>o?.fulfillment?.token===t)?.fulfillment||null}
async function agentBurst(){const l=await ledger();for(let i=0;i<WORKLOAD;i++)await runAgentCycle({ledger:l,baseUrl:PUBLIC})}
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function marketHtml(id,page=1,q=''){const stores=marketStores(),store=id?stores.find(x=>x.id===id):null,per=60,total=store?.products||marketStats().products,pages=Math.ceil(total/per),p=Math.max(1,Math.min(page,pages)),items=catalogPage({storeId:id||undefined,offset:(p-1)*per,limit:per,query:q}),nav=stores.map(x=>`<a href="/market/${x.id}">${esc(x.name)}</a>`).join(' ');return `<!doctype html><meta name="viewport" content="width=device-width"><title>ULTRON AI Market</title><style>body{background:#090c10;color:#fff;font:15px system-ui;max-width:1250px;margin:auto;padding:24px}nav{display:flex;gap:8px;flex-wrap:wrap}a{color:#8cff8c}section{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}article{background:#141920;padding:18px;border-radius:14px}b{font-size:28px;color:#6ee77a}</style><h1>${esc(store?.name||'ULTRON AI Market Network')}</h1><p>10 stores · ${marketStats().products.toLocaleString()} digital products · $1–$999 · PayPal checkout · verified-payment fulfillment.</p><form><input name="q" value="${esc(q)}" placeholder="Search products"><button>Search</button></form><nav>${nav}</nav><section>${items.map(x=>`<article><small>${esc(x.category)}</small><h3>${esc(x.name)}</h3><b>$${x.price}</b><p>${esc(x.description)}</p><a href="/buy?product=${x.id}">Buy with PayPal</a></article>`).join('')}</section><p>Page ${p}/${pages}</p>`}
export function createApp(){return createServer(async(req,res)=>{const u=new URL(req.url,'http://local'),path=u.pathname,json=(s,d)=>{res.writeHead(s,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(d))};try{
if(path==='/health'){const db=await storeHealth(),a=await agentState();return json(db.ok?200:503,{ok:db.ok,database:db,aiMarket:{ready:true,...marketStats()},paymentReady:READY&&payment.ok,agents:{lastCycleAt:a.metrics?.lastCycleAt||null,intervalMinutes:INTERVAL,workloadMultiplier:WORKLOAD}})}
if(path==='/api/market')return json(200,{ok:true,stats:marketStats(),stores:marketStores()});
if(path==='/api/ultron2')return json(200,{ok:true,manifest:capabilityManifest(),market:marketStats(),agentIntervalMinutes:INTERVAL,workloadMultiplier:WORKLOAD});
if(path==='/api/wizard'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;const project=wizardFromConversation(raw?JSON.parse(raw):{});await saveProject(project);return json(200,{ok:true,project})}
if(path==='/api/projects'&&req.method==='GET')return json(200,{ok:true,projects:await listProjects()});
if(path.startsWith('/api/projects/')&&req.method==='GET'){const id=decodeURIComponent(path.slice('/api/projects/'.length));const project=await getProject(id);return project?json(200,{ok:true,project}):json(404,{error:'project not found'})}
if(path==='/api/project-progress'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;const b=raw?JSON.parse(raw):{};return json(200,{ok:true,project:await updateProjectProgress(b.projectId,b.milestoneId,b.status)})}
if(path==='/api/candidates'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;return json(200,{ok:true,candidates:generateCandidates(raw?JSON.parse(raw):{})})}
if(path==='/api/critique'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;const b=raw?JSON.parse(raw):{};return json(200,{ok:true,result:critiqueCandidate(b.candidate||{},b.metrics||{})})}
if(path==='/api/acquisition-plan'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;return json(200,{ok:true,plan:buildAcquisitionPlan(raw?JSON.parse(raw):{})})}
if(path==='/api/sales-workflow'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;return json(200,{ok:true,workflow:prospectToPaymentWorkflow(raw?JSON.parse(raw):{})})}
if(path==='/api/video-systems'&&req.method==='GET')return json(200,{ok:true,architecture:unifiedVideoArchitecture()});
if(path==='/api/video-systems/critique'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;return json(200,{ok:true,result:productCritiqueSystem(raw?JSON.parse(raw):{})})}
if(path==='/api/video-systems/app-factory'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;return json(200,{ok:true,result:appFactorySystem(raw?JSON.parse(raw):{})})}
if(path==='/api/video-systems/revenue'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;return json(200,{ok:true,result:prospectRevenueSystem(raw?JSON.parse(raw):{})})}
if(path==='/api/video-systems/wizard'&&req.method==='POST'){let raw='';for await(const ch of req)raw+=ch;const result=wizardOperatingSystem(raw?JSON.parse(raw):{});await saveProject(result.project);return json(200,{ok:true,result})}
if(path==='/api/search')return json(200,{ok:true,items:catalogPage({storeId:u.searchParams.get('store')||undefined,offset:Number(u.searchParams.get('offset')||0),limit:Math.min(100,Number(u.searchParams.get('limit')||20)),query:u.searchParams.get('q')||''})});
if(path==='/market'||path.startsWith('/market/')){res.writeHead(200,{'content-type':'text/html'});return res.end(marketHtml(path==='/market'?null:decodeURIComponent(path.slice(8)),Number(u.searchParams.get('page')||1),u.searchParams.get('q')||''))}
if(path==='/buy'){if(!READY)return json(503,{error:'PayPal not configured'});res.writeHead(303,{location:await createOrder(u.searchParams.get('product')||'')});return res.end()}
if(path==='/paypal/return'){const id=u.searchParams.get('token')||'',c=await capture(id);if(!c||c.status!=='COMPLETED')return json(409,{error:'Capture not completed'});const f=await fulfill(id,c);await agentBurst();res.writeHead(303,{location:'/fulfillment?token='+f.token});return res.end()}
if(path==='/fulfillment'){const f=await byToken(u.searchParams.get('token'));if(!f)return json(404,{error:'Not found'});res.writeHead(200,{'content-type':'text/html'});return res.end(renderFulfillmentHtml(f))}
if(path==='/paypal/cancel')return res.end('<h1>Payment canceled</h1>');
if(path==='/api/payment-status')return json(200,{provider:'PayPal',mode:'live',ready:READY&&payment.ok,runtime:payment});
return json(404,{error:'Not found'})}catch(e){console.error(e);return json(500,{error:'Request failed'})}})}
async function boot(){try{payment=await verifyPayPalRuntime({paypal,webhookId:WH,publicBaseUrl:PUBLIC})}catch(e){payment={ok:false,checkedAt:new Date().toISOString(),error:String(e?.message||e)}}if(process.env.AGENT_AUTORUN!=='false'){await agentBurst().catch(console.error);timer=setInterval(()=>agentBurst().catch(console.error),INTERVAL*60000);timer.unref?.()}}
if(process.argv[1]===fileURLToPath(import.meta.url)){createApp().listen(Number(process.env.PORT||3000),'0.0.0.0',()=>{console.log(`ULTRON market listening: ${marketStats().products} products, ${INTERVAL}m cycle, ${WORKLOAD}x workload`);boot()})}
