// ULTRON unified treasury accounting. Merchant revenue and trading P&L remain separate.
const finite=n=>Number.isFinite(Number(n))?Number(n):0;
export const DIVISIONS=Object.freeze({
 market:{id:'ai-market',name:'ULTRON AI Market',source:'customer-sales',settlement:'PayPal -> business treasury'},
 crypto:{id:'crypto-division',name:'ULTRON Crypto Division',source:'realized-trading-pnl',settlement:'Crypto.com -> linked bank -> business treasury'}
});
export function emptyTreasury(){return {version:1,currency:'USD',updatedAt:null,market:{grossSales:0,refunds:0,fees:0,netRevenue:0,transferredToTreasury:0},crypto:{startingCapital:0,realizedPnl:0,unrealizedPnl:0,fees:0,drawdown:0,availableCash:0,transferredToTreasury:0},treasury:{merchantContributions:0,tradingContributions:0,totalContributions:0},events:[]}}
export function recordMerchantSettlement(state,input={}){const s=structuredClone(state||emptyTreasury()),gross=finite(input.gross),refund=finite(input.refund),fee=finite(input.fee),transfer=finite(input.transfer);s.market.grossSales+=gross;s.market.refunds+=refund;s.market.fees+=fee;s.market.netRevenue=s.market.grossSales-s.market.refunds-s.market.fees;s.market.transferredToTreasury+=transfer;s.treasury.merchantContributions+=transfer;s.treasury.totalContributions=s.treasury.merchantContributions+s.treasury.tradingContributions;s.updatedAt=new Date().toISOString();s.events.unshift({at:s.updatedAt,division:'ai-market',type:'merchant-settlement',gross,refund,fee,transfer,provider:'PayPal'});s.events=s.events.slice(0,500);return s}
export function recordCryptoSnapshot(state,input={}){const s=structuredClone(state||emptyTreasury());for(const k of ['startingCapital','realizedPnl','unrealizedPnl','fees','drawdown','availableCash'])if(input[k]!==undefined)s.crypto[k]=finite(input[k]);s.updatedAt=new Date().toISOString();s.events.unshift({at:s.updatedAt,division:'crypto-division',type:'account-snapshot',realizedPnl:s.crypto.realizedPnl,unrealizedPnl:s.crypto.unrealizedPnl,fees:s.crypto.fees,availableCash:s.crypto.availableCash});s.events=s.events.slice(0,500);return s}
export function recordCryptoTreasuryTransfer(state,input={}){const s=structuredClone(state||emptyTreasury()),amount=Math.max(0,finite(input.amount));if(amount>s.crypto.availableCash)throw Error('transfer exceeds recorded available cash');s.crypto.transferredToTreasury+=amount;s.crypto.availableCash-=amount;s.treasury.tradingContributions+=amount;s.treasury.totalContributions=s.treasury.merchantContributions+s.treasury.tradingContributions;s.updatedAt=new Date().toISOString();s.events.unshift({at:s.updatedAt,division:'crypto-division',type:'treasury-transfer-record',amount,route:'Crypto.com -> linked bank -> business treasury',status:String(input.status||'recorded')});s.events=s.events.slice(0,500);return s}
export function treasurySummary(state=emptyTreasury()){return {divisions:DIVISIONS,market:state.market,crypto:state.crypto,treasury:state.treasury,integrity:{merchantRevenueIncludesTradingPnl:false,tradingPnlReportedAsPayPalSales:false,cryptoSettlementRoute:'linked-bank',withdrawalAutomation:false}}}
