import {createHash} from 'node:crypto';
export class BriefError extends Error {constructor(issues){super(issues.join('; '));this.name='BriefError';this.issues=issues;}}
const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=(value,min,max)=>typeof value==='string'&&value.trim().length>=min&&value.length<=max&&!/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(value);
function sourceUrl(raw){try{const url=new URL(raw);return url.protocol==='https:'&&!url.username&&!url.password?url.href:null}catch{return null}}
export function validateBrief(brief,now=new Date()){
 const issues=[];if(!brief||typeof brief!=='object'||Array.isArray(brief))throw new BriefError(['Structured brief required']);
 for(const [key,min,max] of [['title',8,100],['audience',10,250],['problem',20,800],['objective',20,800],['successCriterion',15,500]])if(!text(brief[key],min,max))issues.push(`${key} must contain ${min}–${max} characters`);
 if(brief.category!=='booking-operations')issues.push('Supported category: booking-operations');
 if(!Number.isSafeInteger(brief.priceCents)||brief.priceCents<100||brief.priceCents>100000)issues.push('priceCents must be an integer from 100 to 100000');
 if(brief.originalityAcknowledged!==true)issues.push('Confirm the brief is original and you have rights to supplied material');
 if(!Array.isArray(brief.evidence)||brief.evidence.length<2||brief.evidence.length>10)issues.push('Provide 2–10 evidence references');
 else{const seen=new Set();brief.evidence.forEach((e,index)=>{const url=sourceUrl(e?.url);if(!url||!text(e?.label,5,150)||!text(e?.relevance,15,500))issues.push(`Evidence ${index+1} needs a public HTTPS URL, label and concrete relevance`);const date=Date.parse(e?.observedAt||'');if(!Number.isFinite(date)||date>now.getTime()+60000)issues.push(`Evidence ${index+1} needs a valid nonfuture observation date`);if(url&&seen.has(url))issues.push('Evidence references must be distinct');if(url)seen.add(url)});}
 if(!Number.isFinite(now.getTime()))issues.push('Generation time must be valid');
 if(issues.length)throw new BriefError(issues);return brief;
}
// Original deterministic templates: source pages are never scraped, quoted or executed.
export function buildProduct(brief,{now=new Date()}={}){
 validateBrief(brief,now);const h=escapeHtml;
 const sections=[
 ['1. Map the current booking flow','Record where an inquiry arrives, who replies, which service is requested, and how the appointment is confirmed. Time three recent examples rather than estimating the average.','Worksheet: inquiry source | received time | first response | service | confirmation | owner'],
 ['2. Define the minimum intake','Ask for the requested service, preferred appointment windows and a contact method. Explain how the contact information will be used. Collect additional details only when necessary for delivery.','Acceptance check: a colleague can route a sample request without asking the customer to repeat information.'],
 ['3. Build a clear response','Acknowledge the request, summarize the service, and explain the next step. Give an accurate response window based on the measured workload. Never confirm a slot until availability is checked.','Original response template: Thanks for your request for [service]. We will check [preferred window] and respond by [time]. Your booking is confirmed only after you receive our confirmation.'],
 ['4. Handle the exceptions','Write separate steps for unavailable appointments, missing information, cancellations and a system outage. Assign an owner and escalation time to each exception.','Worksheet: exception | customer update | responsible person | escalation time | recovery evidence'],
 ['5. Test before automation','Run five synthetic cases: ordinary request, unavailable slot, missing contact information, duplicate inquiry and cancellation. Keep these cases separate from real customer and payment records.','Acceptance check: every case has the correct next step, no duplicate confirmation and a visible human handoff when blocked.'],
 ['6. Measure and improve','Track first-response time, inquiry-to-booking conversion, completed appointments and customer-reported problems. Compare a measured baseline with one change at a time.','Worksheet: week | inquiries | confirmed bookings | completed appointments | median first-response minutes | problems | next experiment']
 ];
 const body=sections.map(([title,content,worksheet])=>`<section><h2>${h(title)}</h2><p>${h(content)}</p><p class="worksheet">${h(worksheet)}</p></section>`).join('');
 const references=brief.evidence.map(e=>`<li><a href="${h(sourceUrl(e.url))}" rel="noopener noreferrer">${h(e.label)}</a> — observed ${h(e.observedAt)}. These supplied references have not been independently fetched or verified.</li>`).join('');
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${h(brief.title)}</title><style>body{font:17px/1.6 system-ui,sans-serif;max-width:800px;margin:auto;padding:24px;color:#17283a;background:#fff}header,section{border-bottom:1px solid #ccd7e1;padding:18px 0}h1{line-height:1.15}h2{font-size:1.3em}.worksheet{background:#f1f5f9;padding:14px}small{color:#425569}@media print{body{padding:0}section{break-inside:avoid}}</style></head><body><header><small>ORIGINAL DRAFT · OWNER REVIEW REQUIRED</small><h1>${h(brief.title)}</h1><p>For ${h(brief.audience)}</p><p>Problem: ${h(brief.problem)}</p><p>Objective: ${h(brief.objective)}</p><p>Success check: ${h(brief.successCriterion)}</p></header>${body}<section><h2>Evidence and limits</h2><ul>${references}</ul><p>This guide is a reusable operations starting point. It does not connect a calendar, send messages, collect payment or prove customer demand. Check your actual workflow, permissions, pricing and refund terms before selling or installing automation.</p></section><footer><p>Generated ${h(now.toISOString())}. Original template text; no source text was copied.</p></footer></body></html>`;
 const manifest={schemaVersion:1,status:'draft',category:brief.category,title:brief.title,priceCents:brief.priceCents,currency:'USD',createdAt:now.toISOString(),sha256:createHash('sha256').update(html).digest('hex'),quality:{structuredBrief:true,evidenceReferences:brief.evidence.length,sourceContentCopied:false,independentlyVerifiedEvidence:false,originalityAcknowledged:true,sections:sections.length,ownerReviewRequired:true},publication:{published:false,automaticallyAuthorized:false,requiredChecks:['Confirm source relevance and actual customer demand','Review final product and test its worksheets','Confirm price, refund policy and delivery attachment','Authorize the destination and publish action']}};
 return {html,manifest};
}
